### ISSUE TITLE
Unrecognised graphics mode with index (int(vendor)).

### ISSUE THREAD

**Issue by m0nk3h** [Baldomo/asusctltray#11]
Message was "Please open a new issue on Github with this bug report!"

OS: Garuda Linux x86_64
Host: ROG Flow X13 GV301QH_GV301QH 1.0
Kernel: 5.15.14-xanmod1-rog-1
DE: Plasma 5.23.5 (Wayland)

g14/asusctl 4.0.7.r0.gba40c3f-2 [0B 9.82MiB] [Installed]
    Asus laptop control utilities

**Comment by Baldomo** [comment]
Sorry for the late response, could you please try again with the latest commit? The dialog is supposed to actually print a number instead of `int(vendor)` but I hadn't tested that code path yet. Since you have a X13, is `asusctltray` working fine in general? Please feel free to open issues for anything broken, since I don't really know many people with an X13 and I don't have a way of testing everything on my G14.

**Comment by m0nk3h** [comment]
Hi, I have just tested the latest commit, and it is working again. I am only seeing Integrated listed as an option for Graphics, but I do have the Nvidia dGPU disabled with a script, so this may be working as intended. Asusctltray was working fine when I installed Garuda a month or so ago, but at some point stopped working. I don't know when that was, as at this time of year I have the dGPU disabled to save power, and only noticed it wasn't in the system tray when I was testing vfio mode for a recent supergfxctl update. I'm on the asus-linux.org discord server as LaoTsu, if you need anything else testing on the X13. Thanks for resolving the bug.

**Comment by Baldomo** [comment]
I see. It could have been just a fritz on `supergfxctl`'s side, since `asusctl-gex` (the official GNOME shell extension) also has a check for a "uknown" graphics mode (and then it just ignores it). Thank you for letting me know, I'll close this issue for the time being.
