### ISSUE TITLE
Add dGPU power status to tray

### ISSUE THREAD

**Issue by m0nk3h** [Baldomo/asusctltray#14]
Would you think that adding a status line or icon to indicate the power status of the dGPU (supergfxctl -S) to show if it's active or suspended would be worthwhile?  It's a command I run fairly regularly to check the dGPU is suspended properly.

Hopefully, the image below shows how the gnome tool presents the info. 

[image](https://user-images.githubusercontent.com/56454463/153286005-d6599784-05b4-458f-8b22-866d1d43aafc.png)

**Comment by Baldomo** [comment]
Thank you for the suggestion! I was actually planning on implementing it at some point and it can be done without much hassle of course. Adding a second icon to the tray may be something I'll have to look into because it doesn't sound easy with Gtk. 

Anyways, it'll take me some time to work on this as I'm working on exams at the moment. Expect a new commit in the next couple weeks or so.

**Comment by Baldomo** [comment]
Update: I added the status indicator in 8665f1f but the second icon (like asusctl-gex does) is really quite hard to add with the Python AppIndicator bindings, as they only let the user add a single icon by filename. Since creating multiple icons (one for each power status and GPU type) is out of the question and I can't really generate icons on the fly for AppIndicator, I will halt any extra research on the subject. The power indicator can be found in the popup menu anyways.

I will close this issue for the time being and thanks again for the suggestion.
