### ISSUE TITLE
Missing tray icon

### ISSUE THREAD

**Issue by AFAgarap** [Baldomo/asusctltray#16]
Hello! Thanks for working on this program.

I am currently using sway + waybar on Fedora 36, and when I have `asusctltray` running, the ROG icon isn't displayed. May I ask how can I resolve this? 

![image](https://user-images.githubusercontent.com/11130276/178745932-40e32cbf-531a-49e4-989f-028a07575d5a.png)

`asusctltray` is the one on the right of Discord. Thanks

**Comment by Baldomo** [comment]
Thank you for reporting this! I had yet to check for bugs and stuff in wayland, since I still use x11. I assumed `libappindicator` worked fine on wayland but apparently it has its issues. I'll do some test tomorrow and report back to this issue.

**Comment by Baldomo** [comment]
Okay so I can confirm appindicator-based apps are having a lot of trouble working on waybar, there's a (closed) issue here: Alexays/Waybar/issues/21. Sadly this seems to be a waybar-specific bug so I can't do much about it and I'll close his issue for the time being. I also tested `asusctltray` on Gnome + Wayland and it works fine so that confirms the bug is waybar-specific. I suggest you comment on the issue linked above or anyways take it up to thei dev team. Thank you for the report anyways!

**Comment by AFAgarap** [comment]
Thanks for your response!
