### ISSUE TITLE
Wrap the project into a namespace for easy killing on WM reset

### ISSUE THREAD

**Issue by bhalalansh** [Baldomo/asusctltray#18]
Can anyone step up and make it possible to wrap the project in a namespace so that it can be easily killed when the window manager users reload the window manager (`pkill asusctltray`). And/OR optionally allow only one instance to run at a time?

**Comment by Baldomo** [comment]
Sure, I can implement instance checking fairly easily, but what do you mean by "namespace"? I don't suppose you're referring to Linux process namespaces because I can't see how those would be influenced by a window manager. If you'd like to give more info on that, we could try working out a solution.

**Comment by bhalalansh** [comment]
So basically what I am talking is how there is other applications that keep put in the appindicator (trayicons) usually have like this namespace(linux process name) which when you use 
```bash
pkill <appname>
```
the app (the appindicator) will shutoff, which is not the case for this project. It shows only one thing: "python3" or "python"

**Comment by bhalalansh** [comment]
So for example here is leftwm's example for how they kill the custom trayicon stuff on reload and then start them on the end of reload:

fairly they have two files, namely up and down

up: https://github.com/AethanFoot/leftwm-theme-dracula-rounded/blob/master/up

down: https://github.com/AethanFoot/leftwm-theme-dracula-rounded/blob/master/down

**Comment by bhalalansh** [comment]
Actually this might be quite easy, as i saw this: https://code.google.com/archive/p/procname/

**Comment by Baldomo** [comment]
Sorry for the late response! Sure, I can work something out for that, but I'm going to treat as a low priority issue because I feel like this is more cosmetic than anything (since changing the process name is basically hacking around the Linux process namespaces working correctly). I'll work on it in the next couple days and report back.

**Comment by bhalalansh** [comment]
Alright

**Comment by Baldomo** [comment]
Sorry, it's been quite a while. I have had time ti investigate this and I don't think it will ever be implemented. others are welcome to try bu this is a purely cosmetic issue. Feel free to reopen it in the future
